# Generated by Django 5.0.5 on 2024-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEstadoLicencias',
            fields=[
                ('id_estado_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_estado_licencia',
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('serial_contrato', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_licencias', models.IntegerField()),
                ('costo_unitario', models.IntegerField()),
                ('costo_total', models.IntegerField()),
            ],
            options={
                'db_table': 'contratos',
            },
        ),
    ]
