# Generated by Django 5.0.5 on 2024-06-24 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licencias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='serial_contrato',
            new_name='sereal',
        ),
    ]
