# Generated by Django 5.0.5 on 2024-06-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licencias', '0002_rename_serial_contrato_contratos_sereal'),
        ('activosTI', '0039_delete_asignacionlicenciapersona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenciaArea',
            fields=[
                ('id_licencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_licencia', models.CharField(db_column='nombre_licencia', max_length=50, verbose_name='Nombre Licencia')),
                ('sereal', models.CharField(db_column='sereal', max_length=50, verbose_name='Serial')),
                ('fecha_vencimiento', models.DateField(db_column='fecha_vencimiento', verbose_name='Fecha Vencimiento')),
                ('no_ticket', models.CharField(db_column='no_ticket', max_length=20)),
                ('cantidad', models.IntegerField(verbose_name='Numero Licencias')),
                ('id_ceco', models.ForeignKey(db_column='id_ceco', on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.catcentrocosto', verbose_name='Centro de Costo')),
                ('id_contrato', models.ForeignKey(db_column='id_contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='Licencias.contratos')),
                ('id_estado_licencia', models.ForeignKey(db_column='estado_licencia', on_delete=django.db.models.deletion.DO_NOTHING, to='Licencias.catestadolicencias')),
                ('id_responsable', models.ForeignKey(db_column='id_responsable', on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.persona', verbose_name='Responsable')),
            ],
            options={
                'db_table': 'licencias_area',
            },
        ),
    ]
