# Generated by Django 5.0.5 on 2024-06-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Licencias', '0006_upgradelicenciasarea'),
        ('activosTI', '0039_delete_asignacionlicenciapersona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionLicenciaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_licencia', models.ForeignKey(db_column='id_licencia', on_delete=django.db.models.deletion.DO_NOTHING, to='Licencias.licenciapersona')),
                ('id_trabajador', models.ForeignKey(blank=True, db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.persona')),
            ],
            options={
                'db_table': 'asignacion_licencia_persona',
                'unique_together': {('id_trabajador', 'id_licencia')},
            },
        ),
    ]
