# Generated by Django 5.0.5 on 2024-06-24 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0004_alter_catubicacion_nombre'),
        ('Licencias', '0007_asignacionlicenciapersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionLicenciasEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='Equipos.equipo')),
                ('id_licencia', models.ForeignKey(db_column='id_licencia', on_delete=django.db.models.deletion.DO_NOTHING, to='Licencias.licenciasequipo')),
            ],
            options={
                'db_table': 'asignacion_licencias_equipo',
                'unique_together': {('id_equipo', 'id_licencia')},
            },
        ),
    ]
