# Generated by Django 5.0.5 on 2024-06-25 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Licencias', '0008_asignacionlicenciasequipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='licenciaarea',
            old_name='id_ceco',
            new_name='id_centro_costo',
        ),
    ]
