# Generated by Django 5.0.5 on 2024-07-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComplementosActivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicaciones',
            name='fecha_instalacion',
        ),
        migrations.AddField(
            model_name='asignacionaplicaciones',
            name='fecha_instalacion',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
