# Generated by Django 5.0.4 on 2024-04-19 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalianza',
            options={},
        ),
    ]
