# Generated by Django 5.0.4 on 2024-04-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0002_alter_catarea_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catarea',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catarea',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catarea',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='catarea',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
