# Generated by Django 5.0.4 on 2024-04-19 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0002_alter_catalianza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catarea',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catcargo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catestadopersona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catregion',
            options={},
        ),
    ]
