# Generated by Django 5.0.4 on 2024-04-24 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0003_remove_catarea_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicaciones',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catalianza',
            options={},
        ),
    ]
