# Generated by Django 5.0.4 on 2024-04-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0004_alter_aplicaciones_options_alter_catalianza_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcargo',
            options={},
        ),
        migrations.RemoveField(
            model_name='catalianza',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catalianza',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catalianza',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='catalianza',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
