# Generated by Django 5.0.4 on 2024-04-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0005_alter_catcargo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcoordinadores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catdiscoduro',
            options={},
        ),
        migrations.RemoveField(
            model_name='catcargo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catcargo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catcargo',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='catcargo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
