# Generated by Django 5.0.4 on 2024-04-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0006_alter_catcoordinadores_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catestadolicenciapersona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catestadoperiferico',
            options={},
        ),
    ]
