# Generated by Django 5.0.4 on 2024-04-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0007_alter_catestadolicenciaequipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catestadopersona',
            options={},
        ),
        migrations.RemoveField(
            model_name='catestadolicenciaequipo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadolicenciaequipo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadolicenciaequipo',
            name='usuario_registro',
        ),
        migrations.RemoveField(
            model_name='catestadolicenciapersona',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadolicenciapersona',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadolicenciapersona',
            name='usuario_registro',
        ),
        migrations.RemoveField(
            model_name='catestadoperiferico',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadoperiferico',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadoperiferico',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='catestadolicenciaequipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catestadolicenciapersona',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catestadoperiferico',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
