# Generated by Django 5.0.4 on 2024-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0008_alter_catestadoequipo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catmemoriaram',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catprocesador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catregion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cattipoequipo',
            options={},
        ),
        migrations.RemoveField(
            model_name='catestadoequipo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadoequipo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadoequipo',
            name='usuario_registro',
        ),
        migrations.RemoveField(
            model_name='catestadopersona',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadopersona',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catestadopersona',
            name='usuario_registro',
        ),
        migrations.RemoveField(
            model_name='catmarcaequipo',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catmarcaequipo',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catmarcaequipo',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='catestadoequipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catestadopersona',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catmarcaequipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
