# Generated by Django 5.0.4 on 2024-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0009_alter_catmemoriaram_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catregion',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catregion',
            name='usuario_actualizacion',
        ),
        migrations.RemoveField(
            model_name='catregion',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='catregion',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
