# Generated by Django 5.0.4 on 2024-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0011_alter_cattipopropiedad_options_and_more'),
    ]

    operations = [
    ]
