# Generated by Django 5.0.4 on 2024-04-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0012_remove_cattipopropiedad_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenciapersona',
            options={},
        ),
    ]
