# Generated by Django 5.0.4 on 2024-04-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0013_alter_equipo_options_alter_licenciapersona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenciapersona',
            options={'managed': False},
        ),
    ]
