# Generated by Django 5.0.4 on 2024-04-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0014_alter_equipo_options_alter_licenciapersona_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catarea',
            options={'verbose_name': 'area', 'verbose_name_plural': 'Areas'},
        ),
    ]
