# Generated by Django 5.0.4 on 2024-04-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0015_alter_catarea_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoAsignacion',
        ),
    ]
