# Generated by Django 5.0.4 on 2024-04-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0016_delete_historicoasignacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoequipos',
            options={'managed': True},
        ),
    ]
