# Generated by Django 5.0.4 on 2024-04-26 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0017_alter_historicoequipos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoEquipos',
        ),
    ]
