# Generated by Django 5.0.4 on 2024-04-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0018_delete_historicoequipos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolicencias',
            options={'managed': True},
        ),
    ]
