# Generated by Django 5.0.4 on 2024-04-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0019_alter_historicolicencias_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolicencias',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='historicopersonas',
            options={'managed': True},
        ),
    ]
