# Generated by Django 5.0.4 on 2024-04-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0020_alter_historicolicencias_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoPersonas',
        ),
    ]
