# Generated by Django 5.0.4 on 2024-04-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0022_alter_historicolicencias_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricoLicencias',
        ),
    ]
