# Generated by Django 5.0.4 on 2024-04-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0024_historicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='correo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='email', to='activosTI.historicos', verbose_name='Correo Usuario'),
        ),
    ]
