# Generated by Django 5.0.4 on 2024-04-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0025_alter_historicos_correo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='correo_usuario',
            field=models.EmailField(max_length=254, verbose_name='Correo Usuario'),
        ),
    ]
