# Generated by Django 5.0.4 on 2024-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0026_alter_historicos_correo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='fecha_registro',
            field=models.DateTimeField(verbose_name='Fecha de Registro'),
        ),
    ]
