# Generated by Django 5.0.4 on 2024-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0027_alter_historicos_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
    ]
