# Generated by Django 5.0.4 on 2024-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0028_alter_historicos_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicos',
            name='valor_anterior',
            field=models.CharField(default='', max_length=255, verbose_name='Valor Anterior'),
        ),
        migrations.AddField(
            model_name='historicos',
            name='valor_nuevo',
            field=models.CharField(default='', max_length=255, verbose_name='Valor Nuevo'),
        ),
    ]
