# Generated by Django 5.0.4 on 2024-04-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0029_historicos_valor_anterior_historicos_valor_nuevo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='tipo_activo',
            field=models.CharField(max_length=100, verbose_name='Tipo Activo'),
        ),
    ]
