# Generated by Django 5.0.4 on 2024-04-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0030_alter_historicos_tipo_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='activo_modificado',
            field=models.CharField(max_length=100, verbose_name='Activo Modificado'),
        ),
        migrations.AlterField(
            model_name='historicos',
            name='tipo_cambio',
            field=models.CharField(max_length=100, verbose_name='Tipo De Cambio'),
        ),
    ]
