# Generated by Django 5.0.5 on 2024-05-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0031_alter_historicos_activo_modificado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatCentroCosto',
            fields=[
                ('id_centro_costo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'cat_centro_costo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoGeneral',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField()),
                ('correo_usuario', models.CharField(max_length=254)),
                ('tipo_cambio', models.CharField(max_length=100)),
                ('tipo_activo', models.CharField(max_length=100)),
                ('activo_modificado', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_anterior', models.CharField(max_length=255)),
                ('valor_nuevo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'historico_general',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LicenciaArea',
            fields=[
                ('id_licencia_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_licencia_area', models.CharField(max_length=50)),
                ('sereal', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('no_ticket', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'db_table': 'licencia_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpgradeLicenciasArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=20)),
                ('cant_solicitada', models.IntegerField()),
                ('tipo_upgrade', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'upgrade_licencias_area',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='aplicaciones',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catarea',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catcargo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catcoordinadores',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catdiscoduro',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestadoequipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestadolicenciaequipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestadolicenciapersona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestadoperiferico',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catestadopersona',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmarcaequipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catmemoriaram',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catprocesador',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catregion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catso',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cattipoequipo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cattipopropiedad',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='catubicacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contratos',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Historicos',
        ),
    ]
