# Generated by Django 5.0.5 on 2024-05-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0032_authtokentoken_catcentrocosto_historicogeneral_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicogeneral',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
    ]
