# Generated by Django 5.0.5 on 2024-06-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0033_alter_historicogeneral_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historicos',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('correo_usuario', models.EmailField(max_length=254, verbose_name='Correo Usuario')),
                ('tipo_cambio', models.CharField(max_length=100, verbose_name='Tipo De Cambio')),
                ('tipo_activo', models.CharField(max_length=100, verbose_name='Tipo Activo')),
                ('activo_modificado', models.CharField(max_length=100, verbose_name='Activo Modificado')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Historico',
                'verbose_name_plural': 'Historicos',
                'db_table': 'historicos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='HistoricoGeneral',
        ),
    ]
