# Generated by Django 5.0.5 on 2024-06-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0034_historicos_delete_historicogeneral'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicos',
            options={'managed': True, 'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
    ]
