# Generated by Django 5.0.5 on 2024-06-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0035_alter_historicos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicos',
            options={'managed': False, 'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
    ]
