# Generated by Django 5.0.5 on 2024-06-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0036_alter_historicos_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatSo',
        ),
        migrations.DeleteModel(
            name='AsignacionEquipos',
        ),
        migrations.DeleteModel(
            name='AsignacionLicenciasEquipo',
        ),
        migrations.DeleteModel(
            name='CatCoordinadores',
        ),
        migrations.DeleteModel(
            name='CatDiscoduro',
        ),
        migrations.DeleteModel(
            name='CatEstadoequipo',
        ),
        migrations.DeleteModel(
            name='CatMarcaequipo',
        ),
        migrations.DeleteModel(
            name='CatMemoriaram',
        ),
        migrations.DeleteModel(
            name='CatProcesador',
        ),
        migrations.DeleteModel(
            name='CatTipoequipo',
        ),
        migrations.DeleteModel(
            name='CatTipopropiedad',
        ),
        migrations.DeleteModel(
            name='CatUbicacion',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
