# Generated by Django 5.0.5 on 2024-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0037_delete_catso_delete_asignacionequipos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEquipos',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega_equipo', models.DateField()),
                ('fecha_devolucion_equipo', models.DateField()),
            ],
            options={
                'db_table': 'asignacion_equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionLicenciasEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'asignacion_licencias_equipo',
                'managed': False,
            },
        ),
    ]
