# Generated by Django 5.0.5 on 2024-06-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0038_asignacionequipos_asignacionlicenciasequipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionLicenciaPersona',
        ),
        migrations.DeleteModel(
            name='AsignacionLicenciasEquipo',
        ),
        migrations.DeleteModel(
            name='CatEstadoLicenciaequipo',
        ),
        migrations.DeleteModel(
            name='CatEstadoLicenciapersona',
        ),
        migrations.DeleteModel(
            name='Contratos',
        ),
        migrations.DeleteModel(
            name='LicenciaArea',
        ),
        migrations.DeleteModel(
            name='LicenciaPersona',
        ),
        migrations.DeleteModel(
            name='LicenciasEquipo',
        ),
        migrations.DeleteModel(
            name='UpgradeLicenciasArea',
        ),
    ]
