# Generated by Django 5.0.5 on 2024-06-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0039_delete_asignacionlicenciapersona_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aplicaciones',
        ),
        migrations.DeleteModel(
            name='AsignacionAplicaciones',
        ),
    ]
