# Generated by Django 5.0.5 on 2024-06-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0040_delete_aplicaciones_delete_asignacionaplicaciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsignacionEquipos',
        ),
        migrations.DeleteModel(
            name='CatEstadoPeriferico',
        ),
        migrations.DeleteModel(
            name='KitPerifericos',
        ),
        migrations.DeleteModel(
            name='Perifericos',
        ),
    ]
