# Generated by Django 5.0.5 on 2024-07-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0041_delete_asignacionequipos_delete_catestadoperiferico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcentrocosto',
            options={},
        ),
    ]
