# Generated by Django 5.0.5 on 2024-07-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0042_alter_catcentrocosto_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcentrocosto',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
