# Generated by Django 5.0.5 on 2024-07-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0043_alter_catcentrocosto_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catarea',
            options={},
        ),
    ]
