# Generated by Django 5.0.5 on 2024-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0044_alter_catarea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarea',
            name='fecha_registro',
            field=models.DateField(),
        ),
    ]
