# Generated by Django 5.0.5 on 2024-07-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0046_alter_catarea_fecha_registro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcargo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catestadopersona',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catregion',
            options={},
        ),
        migrations.AlterField(
            model_name='catcentrocosto',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
