# Generated by Django 5.0.5 on 2024-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0050_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
