# Generated by Django 5.0.5 on 2024-07-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0051_customuser_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
