# Generated by Django 5.0.5 on 2024-07-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0052_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarea',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='catcargo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
