# Generated by Django 5.0.5 on 2024-07-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0053_alter_catarea_nombre_alter_catcargo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcargo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
