# Generated by Django 5.0.5 on 2024-08-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0054_alter_catcargo_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catarea',
            options={'verbose_name': 'area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='catcargo',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='catcentrocosto',
            options={'verbose_name': 'centro costo', 'verbose_name_plural': 'Centros de Costo'},
        ),
        migrations.AlterModelOptions(
            name='catestadopersona',
            options={'verbose_name': 'estado persona', 'verbose_name_plural': 'Estado Personas'},
        ),
        migrations.AlterModelOptions(
            name='catregion',
            options={'verbose_name': 'region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'managed': False, 'verbose_name': 'persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='catcentrocosto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
