# Generated by Django 5.0.5 on 2024-08-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0055_alter_catarea_options_alter_catcargo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'Personas'},
        ),
    ]
