# Generated by Django 5.0.5 on 2024-08-20 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0056_alter_persona_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Dirección Residencia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_area',
            field=models.ForeignKey(db_column='id_area', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.catarea', verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_cargo',
            field=models.ForeignKey(db_column='id_cargo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.catcargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_centro_costo',
            field=models.ForeignKey(db_column='id_centro_costo', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.catcentrocosto', verbose_name='Centro De Costo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_estado_persona',
            field=models.ForeignKey(db_column='id_estado_persona', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.catestadopersona', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='activosTI.catregion', verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo_institucional',
            field=models.CharField(max_length=50, verbose_name='Correo Institucional'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo_personal',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Correo Personal'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_ingreso_empresa',
            field=models.DateField(verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=30, verbose_name='Numero Identificación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=30, verbose_name='Nombres'),
        ),
    ]
