# Generated by Django 5.0.5 on 2024-08-20 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0057_persona_direccion_persona_id_area_persona_id_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicos',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
    ]
