# Generated by Django 5.0.5 on 2024-08-20 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0058_alter_historicos_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicos',
            name='descripcion',
            field=models.CharField(max_length=500, verbose_name='Descripcion'),
        ),
    ]
