# Generated by Django 5.0.5 on 2024-08-20 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activosTI', '0059_historicos_usuario_alter_historicos_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='DjangoSession',
        )
    ]
