# Generated by Django 5.0.5 on 2024-06-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatCoordinadores',
            fields=[
                ('id_coordinadores', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_coordinadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatDiscoduro',
            fields=[
                ('id_discoduro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_discoduro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstadoequipo',
            fields=[
                ('id_estadoequipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_estadoequipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatMarcaequipo',
            fields=[
                ('id_marcaequipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_marcaequipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatMemoriaram',
            fields=[
                ('id_ram', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_memoriaram',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTipoequipo',
            fields=[
                ('id_tipoequipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_tipoequipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatTipopropiedad',
            fields=[
                ('id_tipopropiedad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_tipopropiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatUbicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=30)),
                ('sereal', models.CharField(max_length=30)),
                ('anydesk', models.CharField(max_length=30)),
                ('procesador', models.CharField(max_length=50)),
                ('costo', models.IntegerField()),
                ('observacion', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'equipo',
                'managed': False,
            },
        ),
    ]
