# Generated by Django 5.0.5 on 2024-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatSo',
            fields=[
                ('id_so', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_registro', models.DateField()),
            ],
            options={
                'db_table': 'cat_so',
            },
        ),
    ]
