# Generated by Django 5.0.5 on 2024-06-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_catso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catubicacion',
            options={},
        ),
    ]
