# Generated by Django 5.0.5 on 2024-06-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0003_alter_catubicacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catubicacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
