# Generated by Django 5.0.5 on 2024-06-26 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0005_catestadoperiferico_kitperifericos_asignacionequipos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipos',
            name='id_equipo',
            field=models.ForeignKey(blank=True, db_column='id_equipo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Equipos.equipo'),
        ),
    ]
