# Generated by Django 5.0.5 on 2024-07-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0006_alter_asignacionequipos_id_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionequipos',
            name='fecha_devolucion_equipo',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asignacionequipos',
            name='id_equipo',
            field=models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.DO_NOTHING, to='Equipos.equipo'),
        ),
    ]
