# Generated by Django 5.0.5 on 2024-07-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0008_alter_asignacionequipos_id_trabajador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitperifericos',
            name='id_perifericos',
        ),
        migrations.AddField(
            model_name='kitperifericos',
            name='perifericos',
            field=models.ManyToManyField(db_table='kit_perifericos_perifericos', to='Equipos.perifericos'),
        ),
    ]
