# Generated by Django 5.0.5 on 2024-07-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0009_remove_kitperifericos_id_perifericos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catestadoperiferico',
            name='fecha_registro',
            field=models.DateField(auto_created=True),
        ),
    ]
