# Generated by Django 5.0.5 on 2024-07-03 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0010_alter_catestadoperiferico_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitperifericos',
            name='perifericos',
            field=models.ManyToManyField(db_table='kit_perifericos_perifericos', related_name='kits', to='Equipos.perifericos'),
        ),
    ]
