# Generated by Django 5.0.5 on 2024-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0011_alter_kitperifericos_perifericos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitperifericos',
            name='perifericos',
            field=models.ManyToManyField(db_table='kit_perifericos_perifericos', to='Equipos.perifericos'),
        ),
    ]
