# Generated by Django 5.0.5 on 2024-07-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0012_alter_kitperifericos_perifericos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catcoordinadores',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catdiscoduro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catestadoequipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catmarcaequipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='catmemoriaram',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cattipoequipo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cattipopropiedad',
            options={},
        ),
        migrations.AlterField(
            model_name='catestadoperiferico',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catso',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catubicacion',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
