# Generated by Django 5.0.5 on 2024-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0013_alter_catcoordinadores_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcoordinadores',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catdiscoduro',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catestadoequipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catmarcaequipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='catmemoriaram',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cattipoequipo',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cattipopropiedad',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
