# Generated by Django 5.0.5 on 2024-08-20 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0014_alter_catcoordinadores_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={},
        ),
    ]
