# Generated by Django 5.0.4 on 2024-04-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='fecha_ingreso_empresa',
            new_name='fecha_ingreso',
        ),
    ]
