# Generated by Django 5.0.4 on 2024-04-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_rename_fecha_ingreso_empresa_persona_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo_institucional',
            field=models.EmailField(blank=True, default='Sin Correo', max_length=254, null=True, verbose_name='Correo Institucional'),
        ),
    ]
